# Generated by Django 4.2.6 on 2023-10-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(max_length=100, verbose_name='Descrição')),
                ('stamp', models.CharField(max_length=100, verbose_name='Selo')),
                ('year', models.DateField(verbose_name='Ano')),
                ('country', models.TextField(max_length=100, verbose_name='Ano')),
                ('genre', models.TextField(max_length=100, verbose_name='Ano')),
                ('quantity', models.IntegerField(verbose_name='Ano')),
            ],
        ),
    ]
